[package]
name = "read_nef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5"
flate2 = "1"
image = "0.25.1"
imagepipe = "0.5.0"
rawloader = "0.37"
